from enum import StrEnum


class ProjectStatus(StrEnum):
    DRAFT = "DRAFT"
    PAPERS_DISCOVERED = "PAPERS_DISCOVERED"
    PAPERS_SELECTED = "PAPERS_SELECTED"
    PROCESSING = "PROCESSING"
    RESEARCH_READY = "RESEARCH_READY"
    ANALYZING = "ANALYZING"
    REVIEW_READY = "REVIEW_READY"
    REPORT_READY = "REPORT_READY"
    PROCESSING_FAILED = "PROCESSING_FAILED"


class PaperStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    VERIFIED = "VERIFIED"
    SAVED = "SAVED"
    ACQUIRING = "ACQUIRING"
    PROCESSING = "PROCESSING"
    INDEXED = "INDEXED"
    READY = "READY"
    METADATA_VERIFICATION_FAILED = "METADATA_VERIFICATION_FAILED"
    PAPER_PROCESSING_FAILED = "PAPER_PROCESSING_FAILED"


class AnswerStatus(StrEnum):
    QUESTION_RECEIVED = "QUESTION_RECEIVED"
    RETRIEVING = "RETRIEVING"
    RERANKING = "RERANKING"
    GENERATING = "GENERATING"
    VERIFYING = "VERIFYING"
    COMPLETE = "COMPLETE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
